#ifndef __TASK_LIST_IF_H__
#define __TASK_LIST_IF_H__

enum {
	/* SYSTEM TASKS */
	AK_TASK_TIMER_ID,

	/* APP TASKS */
	GW_TASK_IF_CONSOLE_ID,
	GW_TASK_CONSOLE_ID,
	GW_TASK_SNMP_ID,
	GW_TASK_CLOUD_ID,
	GW_TASK_IF_ID,
	GW_TASK_DEBUG_MSG_ID,
	GW_TASK_IF_APP_ID,
	GW_TASK_IF_CPU_SERIAL_ID,
	GW_TASK_SM_ID,
	GW_TASK_SENSOR_ID,
	GW_TASK_SYS_ID,
	GW_TASK_PUB_SUB_ID,
	GW_TASK_FW_ID,
	GW_TASK_IF_USB_STICK_RF24_ID,

	/* EOT task ID */
	AK_TASK_LIST_LEN,
};

#endif //__TASK_LIST_IF_H__
